name: Sync Fork

on:
  schedule:
    - cron: '*/60 * * * *' # Check every 60 minutes
  workflow_dispatch: # Allow manual sync on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: SuLab
          base: main
          head: main
